/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")

    // https://github.com/JLLeitschuh/ktlint-gradle
    id("org.jlleitschuh.gradle.ktlint") version "13.0.0"
}

dependencies {
    implementation(project(":json"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.12.1")
}

application {
    // Define the main class for the application.
    mainClass = "joechungmsft.jsonkt.cli.AppKt"
}

// https://stackoverflow.com/a/13172566
tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}
