/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation(project(":json"))
}

application {
    // Define the main class for the application.
    mainClass = "com.github.jsonkt.cli.AppKt"
}

// https://stackoverflow.com/a/13172566
tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}
